#!/bin/bash

bug="$1"

echo -e "Cek Ping: "${bug}
logger "Cek Ping: "${bug}
#	ping -c 5 ${bug} | grep round-trip > /tmp/cping
	
	pms=$(httping -c 5 ${bug} | grep round-trip | cut -d/ -f4)
	msa=$(httping -c 5 ${bug} | grep round-trip | grep -o ms)
	
if [ $msa = "ms" ]; then	
	echo -e "Ping = $pms $msa"
	logger "Ping = $pms $msa"
else
	echo -e "Tidak ada Internet"
	echo -e "Restart Modem"
	sleep 3
	#reboot                             # reboot stb
	#restart                            # restart stb, restart modem, restart router
	autoip                              # auto ganti ip modem
	#hilink info                        # cek modem info
	#/sbin/usb -r                       # reboot modem
	#hilink iphunter                    # ganti ip modem by aryo brokoly
	#python3 /usr/bin/huawei.py         # ganti ip modem by reyre
	#/etc/init.d/network restart        # restart semua interface
	#ifdown wan; sleep 5; ifup wan      # restart interface wan
	#AT^RESET | atinout -/dev/ttyUSB0 - # restart modem rakitan
	#lednet -usb reset > /dev/null 2>&1 # reboot modem by alkhnet
fi	
