#!/bin/bash

# Alamat host yang ingin Anda ping
HOST="google.com"

# Fungsi untuk reboot modem
reboot_modem() {
    echo "$(date +"%Y-%m-%d %H:%M:%S") - Reboot Modem..."
    #reboot                             # reboot stb
    #restart                            # restart stb, restart modem, restart router
    #autoip                             # auto ganti ip modem
    hilink info                        # cek modem info
    #/sbin/usb -r                       # reboot modem
    #hilink iphunter                    # ganti ip modem by aryo brokoly
    #python3 /usr/bin/huawei.py         # ganti ip modem by reyre
    #/etc/init.d/network restart        # restart semua interface
    #ifdown wan; sleep 5; ifup wan      # restart interface wan
    #AT^RESET | atinout -/dev/ttyUSB0 - # restart modem rakitan
    #lednet -usb reset > /dev/null 2>&1 # reboot modem by alkhnet
}

# Variabel untuk menghitung berapa kali ping gagal
failed_count=0

# Waktu tunggu (detik) sebelum reboot modem setelah ping gagal
WAIT_TIME=1

# Loop untuk melakukan Ping dan Reboot Modem
while true; do
    if ping -c 1 $HOST &> /dev/null; then
        echo "$(date +"%Y-%m-%d %H:%M:%S") - Online. Melanjutkan ping..."
        failed_count=0  # Reset hitungan kegagalan jika host berhasil dijangkau
    else
        echo "$(date +"%Y-%m-%d %H:%M:%S") - Offline."
        failed_count=$((failed_count + 1))  # Tingkatkan hitungan kegagalan
        if [ $failed_count -ge 3 ]; then
            echo "$(date +"%Y-%m-%d %H:%M:%S") - Gagal ping sebanyak 3 kali. Reboot Modem..."
            reboot_modem  # Jika sudah ada 3 kegagalan berturut-turut, reboot modem
            failed_count=0  # Reset hitungan kegagalan setelah reboot modem
        fi
    fi
    sleep 5  # Tunggu sebelum memeriksa koneksi lagi
done
