#!/bin/bash

HOST="104.26.7.171"

reboot_modem() {
    echo "$(date +"%Y-%m-%d %H:%M:%S") - Reboot Modem..."
    #reboot                             # reboot stb
    #restart                            # restart stb, restart modem, restart router
    #autoip                             # auto ganti ip modem
    #hilink info                        # cek modem info
    #/sbin/usb -r                       # reboot modem
    #hilink iphunter                    # ganti ip modem by aryo brokoly
    #python3 /usr/bin/huawei.py         # ganti ip modem by reyre
    #/etc/init.d/network restart        # restart semua interface
    #ifdown wan; sleep 5; ifup wan      # restart interface wan
    #AT^RESET | atinout -/dev/ttyUSB0 - # restart modem rakitan
    lednet -usb reset > /dev/null 2>&1  # reboot modem by alkhnet
}

failed_count=0

WAIT_TIME=1

while true; do
    if ping -c 1 $HOST &> /dev/null; then
        echo "$(date +"%Y-%m-%d %H:%M:%S") - Online"
        failed_count=0
    else
        echo "$(date +"%Y-%m-%d %H:%M:%S") - Offline"
        failed_count=$((failed_count + 1))
        if [ $failed_count -ge 15 ]; then
            echo "$(date +"%Y-%m-%d %H:%M:%S") - Gagal ping 15 kali"
            reboot_modem
            failed_count=0
        fi
    fi
    sleep 10  # Tunggu sebelum memeriksa koneksi lagi
done
