#!/bin/bash
# GPIO Wrapper
 
function cek() {
  ifc="${2}"
  ipm=$(ip route | grep "${ifc}" | grep default | cut -d' ' -f3)

  echo -e "Cek Modem : "${ipm}
  logger "Cek Modem : "${ipm}	
	pms=$(ping -c 5 ${ipm} | grep round-trip | cut -d/ -f4)
	msa=$(ping -c 5 ${ipm} | grep round-trip | grep -o ms)

  if [ $msa = "ms" ]; then	
	echo -e "Terhubung : "${ipm}
	logger "Terhubung : "${ipm}
  else
	echo -e "Disconnect : "${ipm}
	logger -e "Disconnect : "${ipm}
	lednet -usb reset > /dev/null 2>&1
  fi
  case "${2}" in
    "*")
        usage
        ;;
  esac
}

function r(){
echo -e "Restarting Modem"
    #reboot                             # reboot stb
    #restart                            # restart stb, restart modem, restart router
    #autoip                             # auto ganti ip modem
    #hilink info                        # cek modem info
    #/sbin/usb -r                       # reboot modem
    #hilink iphunter                    # ganti ip modem by aryo brokoly
    #python3 /usr/bin/huawei.py         # ganti ip modem by reyre
    #/etc/init.d/network restart        # restart semua interface
    #ifdown wan; sleep 5; ifup wan      # restart interface wan
    #AT^RESET | atinout -/dev/ttyUSB0 - # restart modem rakitan
    lednet -usb reset > /dev/null 2>&1  # reboot modem by alkhnet
}

function usage() {
  cat <<EOF
Usage:
  -cek [interface: wwan0, usb0, eth1]
  -r   [Restart Modem]
EOF
}

case "${1}" in
  -cek)
    cek "${2}"
    ;;
  -r)
    r
    ;;
  *)
    usage
    ;;
esac
